//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aramark_pizza_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public string PizzaSize { get; set; }
        public string PizzaToppings { get; set; }
        public string PizzaTypes { get; set; }
        public string Price { get; set; }
        public string CustomerName { get; set; }
    }
}
